'use client'

import { useState } from 'react'
import { Bitcoin, Blocks, Network, ShieldCheck } from 'lucide-react'
import { toast } from 'sonner'
import { useCasino } from '@/lib/store'
import { apiPost } from '@/lib/apiClient'
import { BetPanel } from './GameView'

function Shell({ children }: { children: React.ReactNode }) {
  return <div className="grid min-w-0 gap-4 lg:grid-cols-[1fr_320px] [&>*]:min-w-0"><div className="relative flex min-h-[430px] flex-col justify-center overflow-hidden rounded-3xl border border-white/[0.08] bg-surface-2 p-5 sm:p-8"><div className="absolute right-5 top-5 flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.16em] text-white/45"><span className="h-1.5 w-1.5 rounded-full bg-[#30d158]" /> BTC network live</div>{children}</div></div>
}

export function BtcCrashGame() {
  const { refreshMe } = useCasino(); const activeCurrency = 'BTC'; const [amount, setAmount] = useState(1); const [target, setTarget] = useState(2); const [result, setResult] = useState<number | null>(null); const [busy, setBusy] = useState(false)
  const play = async () => { setBusy(true); try { const r = await apiPost<any>('/api/games/limbo', { currency: activeCurrency, amount, target }); setResult(r.state.crash); await refreshMe(); if (r.win) toast.success(`BTC bertahan di ${r.state.crash.toFixed(2)}×`) } catch (e) { toast.error((e as Error).message) } finally { setBusy(false) } }
  return <Shell><div className="relative text-center"><Bitcoin className="mx-auto mb-4 h-9 w-9 text-white" /><p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-white/60">on-chain volatility</p><div className={`mt-3 font-mono text-[clamp(56px,15vw,110px)] font-semibold leading-none tracking-[-0.06em] ${result && result >= target ? 'text-[#30d158]' : 'text-white'}`}>{result ? `${result.toFixed(2)}×` : '—'}</div><p className="mt-4 text-[12px] text-[#86868b]">Keluar sebelum blok harga runtuh.</p></div><div className="relative mt-10"><div className="h-1 rounded-full bg-[#f7931a]/20"><div className="h-full w-2/3 rounded-full bg-[#f7931a]" /></div></div><div className="relative mt-8 rounded-2xl border border-white/[0.07] bg-black/20 p-4 text-[11px] text-[#86868b]"><ShieldCheck className="mr-1 inline h-3.5 w-3.5 text-[#30d158]" /> Provably fair block hash · hasil server</div><div className="relative mt-4"><BetPanel amount={amount} setAmount={setAmount} currency={activeCurrency} onBet={() => void play()} disabled={busy} betButtonText={busy ? 'Mengunci blok...' : 'Mulai BTC Crash'}><label className="mb-4 block text-[10.5px] font-medium uppercase tracking-wider text-[#86868b]">Target keluar<input type="number" min="1.01" step="0.01" value={target} onChange={(e) => setTarget(Number(e.target.value))} className="mt-1.5 h-10 w-full rounded-xl border border-white/[0.08] bg-surface-3 px-3 font-mono text-white outline-none" /></label></BetPanel></div></Shell>
}

export function HashRunGame() {
  const { refreshMe } = useCasino(); const activeCurrency = 'BTC'; const [amount, setAmount] = useState(1); const [risk, setRisk] = useState<'low'|'medium'|'high'>('medium'); const [bucket, setBucket] = useState<number | null>(null); const [busy, setBusy] = useState(false)
  const play = async () => { setBusy(true); try { const r = await apiPost<any>('/api/games/plinko', { currency: activeCurrency, amount, risk }); setBucket(r.state.bucket); await refreshMe(); if (r.win) toast.success(`Hash mendarat di ${r.multiplier.toFixed(2)}×`) } catch (e) { toast.error((e as Error).message) } finally { setBusy(false) } }
  return <Shell><div className="relative mx-auto w-full max-w-xl"><div className="mb-10 flex items-center justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-white">proof of work</p><h2 className="mt-2 text-2xl font-semibold">Hash Run</h2></div><Blocks className="h-9 w-9 text-white" /></div><div className="grid grid-cols-8 gap-2 rounded-2xl border border-white/[0.07] bg-black/20 p-4">{Array.from({ length: 32 }).map((_, i) => <div key={i} className={`aspect-square rounded-md border transition ${bucket !== null && i % 8 === bucket % 8 ? 'border-[#ffb340] bg-[#ffb340]/50 shadow-[0_0_18px_#ffb340]' : 'border-white/[0.06] bg-white/[0.03]'}`} />)}</div><div className="mt-4 flex justify-between text-[10px] text-[#5c5c66]"><span>GENESIS</span><span>{bucket === null ? 'WAITING FOR HASH' : `BUCKET ${bucket}`}</span><span>CONFIRMED</span></div></div><div className="relative mt-6"><BetPanel amount={amount} setAmount={setAmount} currency={activeCurrency} onBet={() => void play()} disabled={busy} betButtonText={busy ? 'Mining...' : 'Run Hash'}><label className="mb-4 block text-[10.5px] font-medium uppercase tracking-wider text-[#86868b]">Hash difficulty<div className="mt-1.5 grid grid-cols-3 gap-2">{(['low','medium','high'] as const).map((v) => <button key={v} onClick={() => setRisk(v)} className={`h-10 rounded-xl text-[12px] font-semibold capitalize ${risk === v ? 'bg-white text-black' : 'bg-surface-3 text-[#9d9da6]'}`}>{v}</button>)}</div></label></BetPanel></div></Shell>
}

export function SatoshiGridGame() {
  const { refreshMe } = useCasino(); const activeCurrency = 'BTC'; const [amount, setAmount] = useState(1); const [picks, setPicks] = useState<number[]>([]); const [drawn, setDrawn] = useState<number[]>([]); const [busy, setBusy] = useState(false)
  const play = async () => { if (picks.length < 3) return toast.error('Pilih minimal 3 node'); setBusy(true); try { const r = await apiPost<any>('/api/games/keno', { currency: activeCurrency, amount, picks }); setDrawn(r.state.drawn); await refreshMe() } catch (e) { toast.error((e as Error).message) } finally { setBusy(false) } }
  return <Shell><div className="relative"><div className="mb-6 flex items-center justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-white">UTXO selection</p><h2 className="mt-2 text-2xl font-semibold">Satoshi Grid</h2></div><Network className="h-9 w-9 text-white" /></div><div className="grid grid-cols-8 gap-2">{Array.from({ length: 40 }).map((_, i) => { const active = picks.includes(i); const hit = drawn.includes(i); return <button key={i} onClick={() => setPicks((p) => p.includes(i) ? p.filter((x) => x !== i) : p.length < 10 ? [...p, i] : p)} className={`aspect-square rounded-lg border text-[11px] font-mono transition ${hit ? 'border-[#30d158] bg-[#30d158]/25 text-[#30d158]' : active ? 'border-[#ffd60a] bg-[#ffd60a]/20 text-white' : 'border-white/[0.07] bg-white/[0.03] text-[#6a6a73]'}`}>{i + 1}</button> })}</div><div className="mt-4 flex items-center justify-between text-[11px] text-[#86868b]"><span>{picks.length}/10 node dipilih</span><button onClick={() => setPicks([])} className="text-white/60">reset</button></div></div><div className="relative mt-6"><BetPanel amount={amount} setAmount={setAmount} currency={activeCurrency} onBet={() => void play()} disabled={busy} betButtonText={busy ? 'Scanning...' : 'Scan Grid'} /></div></Shell>
}
