/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBetsRouteImport } from './routes/api/bets'
import { Route as ApiChallengesRouteImport } from './routes/api/challenges'
import { Route as ApiFairRouteImport } from './routes/api/fair'
import { Route as ApiFeedRouteImport } from './routes/api/feed'
import { Route as ApiTradeRouteImport } from './routes/api/trade'
import { Route as ApiWalletRouteImport } from './routes/api/wallet'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiGamesBlackjackRouteImport } from './routes/api/games/blackjack'
import { Route as ApiGamesChestRouteImport } from './routes/api/games/chest'
import { Route as ApiGamesDiceRouteImport } from './routes/api/games/dice'
import { Route as ApiGamesKenoRouteImport } from './routes/api/games/keno'
import { Route as ApiGamesLimboRouteImport } from './routes/api/games/limbo'
import { Route as ApiGamesMinesRouteImport } from './routes/api/games/mines'
import { Route as ApiGamesPlinkoRouteImport } from './routes/api/games/plinko'
import { Route as ApiGamesRouletteRouteImport } from './routes/api/games/roulette'
import { Route as ApiGamesSlotsRouteImport } from './routes/api/games/slots'
import { Route as ApiProfileAvatarRouteImport } from './routes/api/profile/avatar'
import { Route as ApiProfileAvatarFileRouteImport } from './routes/api/profile/avatar-file'
import { Route as ApiSyncRestoreRouteImport } from './routes/api/sync/restore'
import { Route as ApiSyncSnapshotRouteImport } from './routes/api/sync/snapshot'
import { Route as ApiWalletFaucetRouteImport } from './routes/api/wallet/faucet'
import { Route as ApiWalletLuckRouteImport } from './routes/api/wallet/luck'
import { Route as ApiWalletSwapRouteImport } from './routes/api/wallet/swap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBetsRoute = ApiBetsRouteImport.update({
  id: '/api/bets',
  path: '/api/bets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChallengesRoute = ApiChallengesRouteImport.update({
  id: '/api/challenges',
  path: '/api/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFairRoute = ApiFairRouteImport.update({
  id: '/api/fair',
  path: '/api/fair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedRoute = ApiFeedRouteImport.update({
  id: '/api/feed',
  path: '/api/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTradeRoute = ApiTradeRouteImport.update({
  id: '/api/trade',
  path: '/api/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWalletRoute = ApiWalletRouteImport.update({
  id: '/api/wallet',
  path: '/api/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesBlackjackRoute = ApiGamesBlackjackRouteImport.update({
  id: '/api/games/blackjack',
  path: '/api/games/blackjack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesChestRoute = ApiGamesChestRouteImport.update({
  id: '/api/games/chest',
  path: '/api/games/chest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesDiceRoute = ApiGamesDiceRouteImport.update({
  id: '/api/games/dice',
  path: '/api/games/dice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesKenoRoute = ApiGamesKenoRouteImport.update({
  id: '/api/games/keno',
  path: '/api/games/keno',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesLimboRoute = ApiGamesLimboRouteImport.update({
  id: '/api/games/limbo',
  path: '/api/games/limbo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesMinesRoute = ApiGamesMinesRouteImport.update({
  id: '/api/games/mines',
  path: '/api/games/mines',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesPlinkoRoute = ApiGamesPlinkoRouteImport.update({
  id: '/api/games/plinko',
  path: '/api/games/plinko',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesRouletteRoute = ApiGamesRouletteRouteImport.update({
  id: '/api/games/roulette',
  path: '/api/games/roulette',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesSlotsRoute = ApiGamesSlotsRouteImport.update({
  id: '/api/games/slots',
  path: '/api/games/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileAvatarRoute = ApiProfileAvatarRouteImport.update({
  id: '/api/profile/avatar',
  path: '/api/profile/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileAvatarFileRoute = ApiProfileAvatarFileRouteImport.update({
  id: '/api/profile/avatar-file',
  path: '/api/profile/avatar-file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRestoreRoute = ApiSyncRestoreRouteImport.update({
  id: '/api/sync/restore',
  path: '/api/sync/restore',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncSnapshotRoute = ApiSyncSnapshotRouteImport.update({
  id: '/api/sync/snapshot',
  path: '/api/sync/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWalletFaucetRoute = ApiWalletFaucetRouteImport.update({
  id: '/faucet',
  path: '/faucet',
  getParentRoute: () => ApiWalletRoute,
} as any)
const ApiWalletLuckRoute = ApiWalletLuckRouteImport.update({
  id: '/luck',
  path: '/luck',
  getParentRoute: () => ApiWalletRoute,
} as any)
const ApiWalletSwapRoute = ApiWalletSwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => ApiWalletRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/bets': typeof ApiBetsRoute
  '/api/challenges': typeof ApiChallengesRoute
  '/api/fair': typeof ApiFairRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/trade': typeof ApiTradeRoute
  '/api/wallet': typeof ApiWalletRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/games/blackjack': typeof ApiGamesBlackjackRoute
  '/api/games/chest': typeof ApiGamesChestRoute
  '/api/games/dice': typeof ApiGamesDiceRoute
  '/api/games/keno': typeof ApiGamesKenoRoute
  '/api/games/limbo': typeof ApiGamesLimboRoute
  '/api/games/mines': typeof ApiGamesMinesRoute
  '/api/games/plinko': typeof ApiGamesPlinkoRoute
  '/api/games/roulette': typeof ApiGamesRouletteRoute
  '/api/games/slots': typeof ApiGamesSlotsRoute
  '/api/profile/avatar': typeof ApiProfileAvatarRoute
  '/api/profile/avatar-file': typeof ApiProfileAvatarFileRoute
  '/api/sync/restore': typeof ApiSyncRestoreRoute
  '/api/sync/snapshot': typeof ApiSyncSnapshotRoute
  '/api/wallet/faucet': typeof ApiWalletFaucetRoute
  '/api/wallet/luck': typeof ApiWalletLuckRoute
  '/api/wallet/swap': typeof ApiWalletSwapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/bets': typeof ApiBetsRoute
  '/api/challenges': typeof ApiChallengesRoute
  '/api/fair': typeof ApiFairRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/trade': typeof ApiTradeRoute
  '/api/wallet': typeof ApiWalletRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/games/blackjack': typeof ApiGamesBlackjackRoute
  '/api/games/chest': typeof ApiGamesChestRoute
  '/api/games/dice': typeof ApiGamesDiceRoute
  '/api/games/keno': typeof ApiGamesKenoRoute
  '/api/games/limbo': typeof ApiGamesLimboRoute
  '/api/games/mines': typeof ApiGamesMinesRoute
  '/api/games/plinko': typeof ApiGamesPlinkoRoute
  '/api/games/roulette': typeof ApiGamesRouletteRoute
  '/api/games/slots': typeof ApiGamesSlotsRoute
  '/api/profile/avatar': typeof ApiProfileAvatarRoute
  '/api/profile/avatar-file': typeof ApiProfileAvatarFileRoute
  '/api/sync/restore': typeof ApiSyncRestoreRoute
  '/api/sync/snapshot': typeof ApiSyncSnapshotRoute
  '/api/wallet/faucet': typeof ApiWalletFaucetRoute
  '/api/wallet/luck': typeof ApiWalletLuckRoute
  '/api/wallet/swap': typeof ApiWalletSwapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/bets': typeof ApiBetsRoute
  '/api/challenges': typeof ApiChallengesRoute
  '/api/fair': typeof ApiFairRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/trade': typeof ApiTradeRoute
  '/api/wallet': typeof ApiWalletRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/games/blackjack': typeof ApiGamesBlackjackRoute
  '/api/games/chest': typeof ApiGamesChestRoute
  '/api/games/dice': typeof ApiGamesDiceRoute
  '/api/games/keno': typeof ApiGamesKenoRoute
  '/api/games/limbo': typeof ApiGamesLimboRoute
  '/api/games/mines': typeof ApiGamesMinesRoute
  '/api/games/plinko': typeof ApiGamesPlinkoRoute
  '/api/games/roulette': typeof ApiGamesRouletteRoute
  '/api/games/slots': typeof ApiGamesSlotsRoute
  '/api/profile/avatar': typeof ApiProfileAvatarRoute
  '/api/profile/avatar-file': typeof ApiProfileAvatarFileRoute
  '/api/sync/restore': typeof ApiSyncRestoreRoute
  '/api/sync/snapshot': typeof ApiSyncSnapshotRoute
  '/api/wallet/faucet': typeof ApiWalletFaucetRoute
  '/api/wallet/luck': typeof ApiWalletLuckRoute
  '/api/wallet/swap': typeof ApiWalletSwapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/bets'
    | '/api/challenges'
    | '/api/fair'
    | '/api/feed'
    | '/api/trade'
    | '/api/wallet'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/games/blackjack'
    | '/api/games/chest'
    | '/api/games/dice'
    | '/api/games/keno'
    | '/api/games/limbo'
    | '/api/games/mines'
    | '/api/games/plinko'
    | '/api/games/roulette'
    | '/api/games/slots'
    | '/api/profile/avatar'
    | '/api/profile/avatar-file'
    | '/api/sync/restore'
    | '/api/sync/snapshot'
    | '/api/wallet/faucet'
    | '/api/wallet/luck'
    | '/api/wallet/swap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/bets'
    | '/api/challenges'
    | '/api/fair'
    | '/api/feed'
    | '/api/trade'
    | '/api/wallet'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/games/blackjack'
    | '/api/games/chest'
    | '/api/games/dice'
    | '/api/games/keno'
    | '/api/games/limbo'
    | '/api/games/mines'
    | '/api/games/plinko'
    | '/api/games/roulette'
    | '/api/games/slots'
    | '/api/profile/avatar'
    | '/api/profile/avatar-file'
    | '/api/sync/restore'
    | '/api/sync/snapshot'
    | '/api/wallet/faucet'
    | '/api/wallet/luck'
    | '/api/wallet/swap'
  id:
    | '__root__'
    | '/'
    | '/api/bets'
    | '/api/challenges'
    | '/api/fair'
    | '/api/feed'
    | '/api/trade'
    | '/api/wallet'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/games/blackjack'
    | '/api/games/chest'
    | '/api/games/dice'
    | '/api/games/keno'
    | '/api/games/limbo'
    | '/api/games/mines'
    | '/api/games/plinko'
    | '/api/games/roulette'
    | '/api/games/slots'
    | '/api/profile/avatar'
    | '/api/profile/avatar-file'
    | '/api/sync/restore'
    | '/api/sync/snapshot'
    | '/api/wallet/faucet'
    | '/api/wallet/luck'
    | '/api/wallet/swap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBetsRoute: typeof ApiBetsRoute
  ApiChallengesRoute: typeof ApiChallengesRoute
  ApiFairRoute: typeof ApiFairRoute
  ApiFeedRoute: typeof ApiFeedRoute
  ApiTradeRoute: typeof ApiTradeRoute
  ApiWalletRoute: typeof ApiWalletRouteWithChildren
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiGamesBlackjackRoute: typeof ApiGamesBlackjackRoute
  ApiGamesChestRoute: typeof ApiGamesChestRoute
  ApiGamesDiceRoute: typeof ApiGamesDiceRoute
  ApiGamesKenoRoute: typeof ApiGamesKenoRoute
  ApiGamesLimboRoute: typeof ApiGamesLimboRoute
  ApiGamesMinesRoute: typeof ApiGamesMinesRoute
  ApiGamesPlinkoRoute: typeof ApiGamesPlinkoRoute
  ApiGamesRouletteRoute: typeof ApiGamesRouletteRoute
  ApiGamesSlotsRoute: typeof ApiGamesSlotsRoute
  ApiProfileAvatarRoute: typeof ApiProfileAvatarRoute
  ApiProfileAvatarFileRoute: typeof ApiProfileAvatarFileRoute
  ApiSyncRestoreRoute: typeof ApiSyncRestoreRoute
  ApiSyncSnapshotRoute: typeof ApiSyncSnapshotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bets': {
      id: '/api/bets'
      path: '/api/bets'
      fullPath: '/api/bets'
      preLoaderRoute: typeof ApiBetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/challenges': {
      id: '/api/challenges'
      path: '/api/challenges'
      fullPath: '/api/challenges'
      preLoaderRoute: typeof ApiChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fair': {
      id: '/api/fair'
      path: '/api/fair'
      fullPath: '/api/fair'
      preLoaderRoute: typeof ApiFairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed': {
      id: '/api/feed'
      path: '/api/feed'
      fullPath: '/api/feed'
      preLoaderRoute: typeof ApiFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trade': {
      id: '/api/trade'
      path: '/api/trade'
      fullPath: '/api/trade'
      preLoaderRoute: typeof ApiTradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wallet': {
      id: '/api/wallet'
      path: '/api/wallet'
      fullPath: '/api/wallet'
      preLoaderRoute: typeof ApiWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/blackjack': {
      id: '/api/games/blackjack'
      path: '/api/games/blackjack'
      fullPath: '/api/games/blackjack'
      preLoaderRoute: typeof ApiGamesBlackjackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/chest': {
      id: '/api/games/chest'
      path: '/api/games/chest'
      fullPath: '/api/games/chest'
      preLoaderRoute: typeof ApiGamesChestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/dice': {
      id: '/api/games/dice'
      path: '/api/games/dice'
      fullPath: '/api/games/dice'
      preLoaderRoute: typeof ApiGamesDiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/keno': {
      id: '/api/games/keno'
      path: '/api/games/keno'
      fullPath: '/api/games/keno'
      preLoaderRoute: typeof ApiGamesKenoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/limbo': {
      id: '/api/games/limbo'
      path: '/api/games/limbo'
      fullPath: '/api/games/limbo'
      preLoaderRoute: typeof ApiGamesLimboRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/mines': {
      id: '/api/games/mines'
      path: '/api/games/mines'
      fullPath: '/api/games/mines'
      preLoaderRoute: typeof ApiGamesMinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/plinko': {
      id: '/api/games/plinko'
      path: '/api/games/plinko'
      fullPath: '/api/games/plinko'
      preLoaderRoute: typeof ApiGamesPlinkoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/roulette': {
      id: '/api/games/roulette'
      path: '/api/games/roulette'
      fullPath: '/api/games/roulette'
      preLoaderRoute: typeof ApiGamesRouletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/slots': {
      id: '/api/games/slots'
      path: '/api/games/slots'
      fullPath: '/api/games/slots'
      preLoaderRoute: typeof ApiGamesSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile/avatar': {
      id: '/api/profile/avatar'
      path: '/api/profile/avatar'
      fullPath: '/api/profile/avatar'
      preLoaderRoute: typeof ApiProfileAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile/avatar-file': {
      id: '/api/profile/avatar-file'
      path: '/api/profile/avatar-file'
      fullPath: '/api/profile/avatar-file'
      preLoaderRoute: typeof ApiProfileAvatarFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/restore': {
      id: '/api/sync/restore'
      path: '/api/sync/restore'
      fullPath: '/api/sync/restore'
      preLoaderRoute: typeof ApiSyncRestoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/snapshot': {
      id: '/api/sync/snapshot'
      path: '/api/sync/snapshot'
      fullPath: '/api/sync/snapshot'
      preLoaderRoute: typeof ApiSyncSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wallet/faucet': {
      id: '/api/wallet/faucet'
      path: '/faucet'
      fullPath: '/api/wallet/faucet'
      preLoaderRoute: typeof ApiWalletFaucetRouteImport
      parentRoute: typeof ApiWalletRoute
    }
    '/api/wallet/luck': {
      id: '/api/wallet/luck'
      path: '/luck'
      fullPath: '/api/wallet/luck'
      preLoaderRoute: typeof ApiWalletLuckRouteImport
      parentRoute: typeof ApiWalletRoute
    }
    '/api/wallet/swap': {
      id: '/api/wallet/swap'
      path: '/swap'
      fullPath: '/api/wallet/swap'
      preLoaderRoute: typeof ApiWalletSwapRouteImport
      parentRoute: typeof ApiWalletRoute
    }
  }
}

interface ApiWalletRouteChildren {
  ApiWalletFaucetRoute: typeof ApiWalletFaucetRoute
  ApiWalletLuckRoute: typeof ApiWalletLuckRoute
  ApiWalletSwapRoute: typeof ApiWalletSwapRoute
}

const ApiWalletRouteChildren: ApiWalletRouteChildren = {
  ApiWalletFaucetRoute: ApiWalletFaucetRoute,
  ApiWalletLuckRoute: ApiWalletLuckRoute,
  ApiWalletSwapRoute: ApiWalletSwapRoute,
}

const ApiWalletRouteWithChildren = ApiWalletRoute._addFileChildren(
  ApiWalletRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBetsRoute: ApiBetsRoute,
  ApiChallengesRoute: ApiChallengesRoute,
  ApiFairRoute: ApiFairRoute,
  ApiFeedRoute: ApiFeedRoute,
  ApiTradeRoute: ApiTradeRoute,
  ApiWalletRoute: ApiWalletRouteWithChildren,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiGamesBlackjackRoute: ApiGamesBlackjackRoute,
  ApiGamesChestRoute: ApiGamesChestRoute,
  ApiGamesDiceRoute: ApiGamesDiceRoute,
  ApiGamesKenoRoute: ApiGamesKenoRoute,
  ApiGamesLimboRoute: ApiGamesLimboRoute,
  ApiGamesMinesRoute: ApiGamesMinesRoute,
  ApiGamesPlinkoRoute: ApiGamesPlinkoRoute,
  ApiGamesRouletteRoute: ApiGamesRouletteRoute,
  ApiGamesSlotsRoute: ApiGamesSlotsRoute,
  ApiProfileAvatarRoute: ApiProfileAvatarRoute,
  ApiProfileAvatarFileRoute: ApiProfileAvatarFileRoute,
  ApiSyncRestoreRoute: ApiSyncRestoreRoute,
  ApiSyncSnapshotRoute: ApiSyncSnapshotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
